export type User = {
  id: number;
  email: string;
  role: string;
  nickname: string;
  telegram_id?: string;
  telegram_username?: string;
};
export type Participant = {
  id: number;
  name: string;
  seed: number;
  player_id: number | null;
  team_id: number | null;
  avatar: string;
};
export type Standing = {
  participant_id: number;
  name: string;
  player_id: number | null;
  team_id: number | null;
  played: number;
  wins: number;
  draws: number;
  losses: number;
  gf: number;
  ga: number;
  gd: number;
  points: number;
  placement_points: number;
  kill_points: number;
};
export type Match = {
  id: number;
  tournament_id: number;
  tournament: string;
  slug: string;
  game: string;
  home: Participant | null;
  away: Participant | null;
  home_score: number | null;
  away_score: number | null;
  winner_id: number | null;
  status: string;
  round: string;
  stage: string;
  group_id: number | null;
  bracket_round_id: number | null;
  scheduled_at: string;
  next_match_id: number | null;
  results: {
    id: number;
    home_score: number;
    away_score: number;
    home_penalties: number | null;
    away_penalties: number | null;
    state: string;
    submitted_by: number;
  }[];
  pubg_results: {
    participant_id: number;
    placement: number;
    kills: number;
    placement_points: number;
    kill_points: number;
    total: number;
  }[];
};
export type Tournament = {
  id: number;
  slug: string;
  name: string;
  game: string;
  format: string;
  mode: string;
  status: string;
  description: string;
  banner: string;
  logo: string;
  max_participants: number;
  participants: number;
  prize_pool: number;
  prizes: Record<string, number>;
  min_team_size: number;
  max_team_size: number;
  start_date: string;
  registration_start: string;
  registration_end: string;
  matches: number;
  completed: number;
  live: number;
  rules: string;
  placement_points: Record<string, number>;
  kill_points: number;
  participant_list: Participant[];
  match_list: Match[];
  groups: { id: number; name: string; standings: Standing[] }[];
  leaderboard: Standing[];
  announcements: { id: number; title: string; body: string }[];
};
export type Player = {
  id: number;
  username: string;
  nickname: string;
  full_name: string;
  region: string;
  avatar: string;
  game_ids: Record<string, string>;
  matches: number;
  wins: number;
  losses: number;
  draws: number;
  win_rate: number;
  points: number;
  titles: number;
  form: string[];
  recent_matches: Match[];
  history: Tournament[];
};
export type Team = {
  id: number;
  name: string;
  logo: string;
  captain_id: number;
  captain: string;
  members: { id: number; name: string; substitute: boolean }[];
  matches: number;
  wins: number;
  losses: number;
  win_rate: number;
  titles: number;
  recent_matches: Match[];
};
export type Registration = {
  id: number;
  tournament_id: number;
  tournament: string;
  game?: string;
  name: string;
  status: string;
  created_at: string;
  user_id?: number;
  nickname?: string;
  full_name?: string;
  region?: string;
  avatar?: string;
  phone?: string;
  game_id?: string;
  telegram_username?: string;
  team_id?: number | null;
  team?: {
    id: number;
    name: string;
    logo?: string;
    captain: string;
    members: { id: number; name: string; substitute: boolean }[];
  } | null;
};
export type AdminData = {
  tournaments: Tournament[];
  registrations: Registration[];
  matches: Match[];
  players: number;
  activity: {
    id: number;
    action: string;
    entity: string;
    entity_id: number;
    created_at: string;
  }[];
  telegram_configured: boolean;
  telegram_linked: boolean;
};
