"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/dialog";
import { Badge, Loading, ErrorState, Empty, Avatar, statusLabels } from "@/components/competition";
import { useApi } from "@/hooks/use-api";
import { mutate } from "@/services/api";
import { date,time,gameName,formatName } from "@/lib/utils";
import type { Tournament, Registration } from "@/types";
export function RegistrationQueue({tournaments,onSaved}:{tournaments:Tournament[];onSaved:()=>void}) {
 const [page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState(''),[game,setGame]=useState(''),[mode,setMode]=useState(''),[tournament,setTournament]=useState(''),[detail,setDetail]=useState<Registration|null>(null),[action,setAction]=useState<{r:Registration;status:string}|null>(null),[busy,setBusy]=useState(false);
 const result=useApi<{items:Registration[];total:number}>(`/admin/registrations?page=${page}&q=${encodeURIComponent(q)}&status=${status}&game=${game}&mode=${mode}${tournament?`&tournament_id=${tournament}`:''}`);
 const filter=(set:(v:string)=>void,v:string)=>{set(v);setPage(1);};
 return <section><div className="section-heading"><div><span className="eyebrow">ISHTIROKCHILAR</span><h2>Arizalarni ko‘rib chiqish</h2><p>{result.data?.total??'—'} ta ariza · Har bir qaror amallar tarixiga yoziladi</p></div></div><div className="queue-filters"><label>Qidirish<input placeholder="Ism, taxallus yoki jamoa" value={q} onChange={e=>filter(setQ,e.target.value)}/></label><label>Turnir<select value={tournament} onChange={e=>filter(setTournament,e.target.value)}><option value="">Barcha turnirlar</option>{tournaments.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Holat<select value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="">Barcha holatlar</option>{['pending','approved','waitlist','rejected'].map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></label><label>O‘yin<select value={game} onChange={e=>filter(setGame,e.target.value)}><option value="">Barcha o‘yinlar</option><option value="efootball">eFootball</option><option value="pubg">PUBG Mobile</option></select></label><label>Rejim<select value={mode} onChange={e=>filter(setMode,e.target.value)}><option value="">Barcha rejimlar</option><option value="solo">Yakka</option><option value="team">Jamoa</option></select></label></div>
 {result.loading?<Loading/>:result.error?<ErrorState message={result.error} retry={result.reload}/>:!result.data?.items.length?<Empty title="Ariza topilmadi" detail="Filtrlarni o‘zgartiring yoki yangi arizalarni kuting."/>:<div className="panel table-scroll"><table><thead><tr><th>Ishtirokchi</th><th>Turnir</th><th>Holat</th><th>Sana (Toshkent)</th><th>Amallar</th></tr></thead><tbody>{result.data.items.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.full_name} · {r.nickname}</small></td><td>{r.tournament}<small>{gameName(r.game||'efootball')} · {r.team?'Jamoa':'Yakka'}</small></td><td><Badge status={r.status}/></td><td>{date(r.created_at)}<small>{time(r.created_at)}</small></td><td><div className="row"><Button size="sm" variant="secondary" onClick={()=>setDetail(r)}>Batafsil</Button>{['approved','waitlist','rejected'].map(s=><Button key={s} size="sm" variant={s==='approved'?'default':'ghost'} disabled={r.status==='approved'||r.status===s||busy} onClick={()=>setAction({r,status:s})}>{s==='approved'?'Tasdiqlash':s==='waitlist'?'Kutishga':'Rad etish'}</Button>)}</div></td></tr>)}</tbody></table></div>}
 {result.data&&result.data.total>20&&<div className="pagination"><Button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Oldingi</Button><span>{page} / {Math.ceil(result.data.total/20)}</span><Button disabled={page*20>=result.data.total} onClick={()=>setPage(p=>p+1)}>Keyingi</Button></div>}
 <Modal open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}} title={detail?.name||'Ariza'} description={detail?.tournament}>{detail&&<div className="form"><div className="entry-summary"><Avatar name={detail.nickname||detail.name} src={detail.avatar}/><div><h3>{detail.full_name}</h3><p>{detail.nickname} · {detail.region||'Hudud ko‘rsatilmagan'}</p></div><Badge status={detail.status}/></div><dl className="detail-grid"><dt>O‘yin ID</dt><dd>{detail.game_id||'Ko‘rsatilmagan'}</dd><dt>Telefon</dt><dd>{detail.phone||'Ko‘rsatilmagan'}</dd><dt>Telegram</dt><dd>{detail.telegram_username?`@${detail.telegram_username}`:'Ulanmagan'}</dd><dt>Yuborilgan</dt><dd>{date(detail.created_at)}, {time(detail.created_at)}</dd></dl>{detail.team&&<><h3>{detail.team.name} · Sardor: {detail.team.captain}</h3>{detail.team.members.map(m=><div className="list-row" key={m.id}><span>{m.name}</span><small>{m.substitute?'Zaxira':'Asosiy tarkib'}</small></div>)}</>}</div>}</Modal>
 <Modal open={!!action} onOpenChange={v=>{if(!v&&!busy)setAction(null);}} title="Qarorni tasdiqlash" description={action?.r.name}><p>{action?.r.tournament}: ariza holati «{statusLabels[action?.status||'']}» bo‘ladi.{action?.status==='approved'?' Tasdiqlangan ishtirokchi turnir tarixiga qo‘shiladi va bu amalni ariza orqali bekor qilib bo‘lmaydi.':''}</p><div className="row"><Button variant="secondary" disabled={busy} onClick={()=>setAction(null)}>Bekor qilish</Button><Button disabled={busy} onClick={async()=>{if(!action)return;setBusy(true);try{await mutate(`/registrations/${action.r.id}`,{status:action.status},'PATCH');toast.success('Ariza holati yangilandi');setAction(null);await result.reload();onSaved();}catch(e){toast.error((e as Error).message);await result.reload();}finally{setBusy(false);}}}>{busy?'Saqlanmoqda…':'Tasdiqlash'}</Button></div></Modal>
 </section>;
}
export function AuditPanel(){const [page,setPage]=useState(1);const r=useApi<{items:{id:number;actor_id:number;action:string;entity:string;entity_id:number;created_at:string}[];total:number}>(`/admin/audit?page=${page}`);return <section><h2>Amallar tarixi</h2><p>Turnir, media, ariza va ruxsat o‘zgarishlari.</p>{r.loading?<Loading/>:r.error?<ErrorState message={r.error} retry={r.reload}/>:<><div className="panel table-scroll"><table><thead><tr><th>Vaqt (Toshkent)</th><th>Foydalanuvchi</th><th>Amal</th><th>Obyekt</th></tr></thead><tbody>{r.data?.items.map(a=><tr key={a.id}><td>{date(a.created_at)} {time(a.created_at)}</td><td>#{a.actor_id}</td><td>{formatName(a.action)}</td><td>{formatName(a.entity)} #{a.entity_id}</td></tr>)}</tbody></table></div>{!r.data?.items.length&&<Empty title="Hali amallar yo‘q" detail="Saqlangan o‘zgarishlar shu yerda ko‘rinadi."/>}<div className="pagination"><Button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Oldingi</Button><span>{page}</span><Button disabled={page*30>=(r.data?.total||0)} onClick={()=>setPage(p=>p+1)}>Keyingi</Button></div></>}</section>;}
export function NotificationPanel(){const r=useApi<{id:number;title:string;body:string;read:boolean;created_at:string}[]>('/notifications');return <section><h2>Bildirishnomalarim</h2>{r.loading?<Loading/>:r.error?<ErrorState message={r.error} retry={r.reload}/>:!r.data?.length?<Empty title="Yangi bildirishnoma yo‘q" detail="Sizga tegishli xabarlar shu yerda ko‘rinadi."/>:<div className="management-list">{r.data.map(n=><article key={n.id}><div><small>{date(n.created_at)} · {time(n.created_at)}</small><h3>{n.title}</h3><p>{n.body}</p></div>{!n.read&&<Button variant="secondary" onClick={async()=>{try{await mutate(`/notifications/${n.id}`,{},'PATCH');await r.reload();}catch(e){toast.error((e as Error).message);}}}>O‘qildi</Button>}</article>)}</div>}</section>;}
