"use client";
import Link from "next/link";
import { MatchCard,TournamentCard,Avatar,Empty,Loading,ErrorState } from "@/components/competition";
import { useApi } from "@/hooks/use-api";
import { date } from "@/lib/utils";
import type { Match,Player,Tournament } from "@/types";
export function HomeActivity(){
 const live=useApi<Match[]>('/matches?status=live&page_size=3',30000),results=useApi<Match[]>('/matches?status=completed&page_size=3'),upcoming=useApi<{items:Tournament[]}>('/tournaments?status=registration&page_size=3'),players=useApi<Player[]>('/leaderboard?page_size=5'),announcements=useApi<{id:number;title:string;body:string;created_at:string}[]>('/announcements');
 return <><section className="section"><div className="section-heading"><div><span className="eyebrow">RAQOBAT DAVOM ETADI</span><h2>Hozir maydonda<span>.</span></h2></div><Link href="/live" className="text-link">O‘yinlar markazi →</Link></div>{live.loading?<Loading/>:live.error?<ErrorState message={live.error} retry={live.reload}/>:live.data?.length?<div className="match-grid">{live.data.map(m=><MatchCard key={m.id} match={m}/>)}</div>:<Empty title="Hozir jonli o‘yin yo‘q" detail="Navbatdagi uchrashuvlar o‘yinlar markazida ko‘rinadi."/>}</section>
 <section className="section"><div className="section-heading"><h2>Qabuldagi turnirlar<span>.</span></h2><Link className="text-link" href="/tournaments">Barchasini ko‘rish →</Link></div>{upcoming.loading?<Loading/>:upcoming.error?<ErrorState message={upcoming.error} retry={upcoming.reload}/>:upcoming.data?.items.length?<div className="tournament-grid">{upcoming.data.items.map(t=><TournamentCard key={t.id} t={t}/>)}</div>:<Empty title="Yangi turnirlar kutilmoqda" detail="Qabul ochilgan turnirlar shu yerda e’lon qilinadi."/>}</section>
 <section className="section"><div className="section-heading"><h2>So‘nggi natijalar<span>.</span></h2></div>{results.loading?<Loading/>:results.error?<ErrorState message={results.error} retry={results.reload}/>:results.data?.length?<div className="match-grid">{results.data.map(m=><MatchCard key={m.id} match={m}/>)}</div>:<Empty title="Natijalar hali yo‘q" detail="Yakunlangan uchrashuvlar shu yerda paydo bo‘ladi."/>}</section>
 <div className="home-community section"><section className="panel prose"><div className="section-heading"><h2>Yetakchi o‘yinchilar</h2><Link className="text-link" href="/leaderboard">Reyting →</Link></div>{players.loading?<Loading/>:players.error?<ErrorState message={players.error} retry={players.reload}/>:players.data?.length?players.data.slice(0,5).map((p,i)=><Link href={`/players/${p.nickname}`} className="list-row ranking-row" key={p.id}><span className="rank-number">{i+1}</span><Avatar name={p.nickname} src={p.avatar}/><div><strong>{p.nickname}</strong><small>{p.region||'ARENA o‘yinchisi'}</small></div><b>{p.points} ochko</b></Link>):<p>Reyting uchun ma’lumot hali yo‘q.</p>}</section><section className="panel prose"><div className="section-heading"><h2>Arena yangiliklari</h2></div>{announcements.loading?<Loading/>:announcements.error?<ErrorState message={announcements.error} retry={announcements.reload}/>:announcements.data?.length?announcements.data.slice(0,3).map(a=><article className="announcement-item" key={a.id}><small>{date(a.created_at)}</small><h3>{a.title}</h3><p>{a.body}</p></article>):<Empty title="Yangi e’lonlar kutilmoqda" detail="Tashkilotchilarning yangiliklari shu yerda e’lon qilinadi."/>}</section></div></>;
}
