"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Modal } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { mutate } from "@/services/api";
import { tashkentInput, toUtc, formatName } from "@/lib/utils";
import type { Tournament } from "@/types";
export function TournamentEditor({t,close,onSaved}:{t:Tournament|null;close:()=>void;onSaved:()=>void}) {
 const [busy,setBusy]=useState(false);
 return <Modal open={!!t} onOpenChange={v=>{if(!v&&!busy)close();}} title="Turnirni tahrirlash" description="Barcha sana va vaqtlar Toshkent vaqti (UTC+5) bilan kiritiladi.">{t&&<form key={t.id} className="form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await mutate(`/tournaments/${t.slug}`,{name:f.get('name'),slug:f.get('slug'),status:f.get('status'),description:f.get('description'),game:f.get('game'),mode:f.get('mode'),format:f.get('format'),max_participants:Number(f.get('max_participants')),min_team_size:Number(f.get('min_team_size')),max_team_size:Number(f.get('max_team_size')),prize_pool:Number(f.get('prize_pool')),prizes:{...t.prizes,'1':Number(f.get('p1')),'2':Number(f.get('p2')),'3':Number(f.get('p3'))},banner:f.get('banner'),logo:f.get('logo'),registration_start:toUtc(String(f.get('registration_start'))),registration_end:toUtc(String(f.get('registration_end'))),start_date:toUtc(String(f.get('start_date'))),end_date:f.get('end_date')?toUtc(String(f.get('end_date'))):null,rules:f.get('rules'),expected_updated_at:t.updated_at},'PUT');toast.success('Turnir yangilandi');close();onSaved();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>
 <div className="form-grid"><label>Turnir nomi<input name="name" required minLength={4} maxLength={120} defaultValue={t.name}/></label><label>Havola nomi<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" defaultValue={t.slug}/></label><label>Holat<select name="status" defaultValue={t.status}>{Object.entries({draft:'Qoralama',registration:'Qabul ochiq',upcoming:'Kutilmoqda',live:'Davom etmoqda',finished:'Yakunlangan'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>O‘yin<select name="game" defaultValue={t.game}><option value="efootball">eFootball</option><option value="pubg">PUBG Mobile</option></select></label><label>Rejim<select name="mode" defaultValue={t.mode}><option value="solo">Yakka</option><option value="team">Jamoa</option></select></label><label>Format<select name="format" defaultValue={t.format}>{['single_elimination','double_elimination','groups_playoffs','league','round_robin'].map(x=><option key={x} value={x}>{formatName(x)}</option>)}</select></label></div>
 <p className="hint">Arizalar mavjud bo‘lsa, havola, o‘yin va format qulflanadi. Jadval tuzilgach qabulni qayta ochib bo‘lmaydi.</p><label>Tavsif<textarea name="description" maxLength={5000} defaultValue={t.description}/></label>
 <div className="form-grid">{(['registration_start','registration_end','start_date','end_date'] as const).map((k,i)=><label key={k}>{['Qabul boshlanishi','Qabul tugashi','Turnir boshlanishi','Turnir yakuni (ixtiyoriy)'][i]}<input type="datetime-local" name={k} required={k!=='end_date'} defaultValue={t[k]?tashkentInput(t[k]):''}/></label>)}<label>Ishtirokchilar chegarasi<input type="number" min={Math.max(2,t.participants)} max={128} name="max_participants" defaultValue={t.max_participants}/></label><label>Asosiy tarkib minimumi<input type="number" min={1} max={10} name="min_team_size" defaultValue={t.min_team_size}/></label><label>Jami tarkib maksimumi<input type="number" min={1} max={12} name="max_team_size" defaultValue={t.max_team_size}/></label><label>Mukofot jamg‘armasi ($)<input type="number" name="prize_pool" min={0} defaultValue={t.prize_pool}/></label>{[1,2,3].map(i=><label key={i}>{i}-o‘rin ($)<input type="number" name={`p${i}`} min={0} defaultValue={t.prizes[String(i)]||0}/></label>)}<label>Banner havolasi<input type="url" name="banner" defaultValue={t.banner}/></label><label>Logo havolasi<input type="url" name="logo" defaultValue={t.logo}/></label></div><label>Qoidalar<textarea name="rules" rows={6} maxLength={20000} defaultValue={t.rules}/></label><Button disabled={busy}>{busy?'Saqlanmoqda…':'O‘zgarishlarni saqlash'}</Button></form>}</Modal>;
}
